# Default values for workspace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

username: user1

tavilySearchApiKey: your-tavily-search-api-key-here

defaultModel:
  name: default-model-name
  apiKey: default-model-key
  url: https://default-model-maas-apicast-production.apps.maas.redhatworkshops.io:443/v1

llamaStackPlayground:
  image: quay.io/rhoai-genaiops/llama-stack-playground:0.2.11-rhone

safetyModel: Llama-Guard-3-1B